### ISSUE TITLE
Robot Service issue

### ISSUE THREAD

**Issue by MatthijsBurgh** [tue-robotics/hero_bringup#97]
```
[robot_service-1] killing on exit
Traceback (most recent call last):
  File "/home/administrator/ros/noetic/system/src/hero_bringup/scripts/hero_robot_service", line 53, in <module>
    service.run()
  File "/home/administrator/ros/noetic/system/src/hero_bringup/src/hero_bringup/robot_service.py", line 421, in run
    self.wait_ready()
  File "/home/administrator/ros/noetic/system/src/hero_bringup/src/hero_bringup/robot_service.py", line 246, in wait_ready
    result = wait_until(lambda: self.diag_pub.get_num_connections() > 0,
  File "/home/administrator/ros/noetic/system/src/hero_bringup/src/hero_bringup/robot_service.py", line 58, in wait_until
    time.sleep(polling)
  File "/home/administrator/ros/noetic/system/src/hero_bringup/src/hero_bringup/robot_service.py", line 219, in signal
    if sig != self.previous_signal:
AttributeError: 'RobotService' object has no attribute 'previous_signal'
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/handlers.py", line 69, in emit
    if self.shouldRollover(record):
  File "/usr/lib/python3.8/logging/handlers.py", line 183, in shouldRollover
    self.stream = self._open()
  File "/usr/lib/python3.8/logging/__init__.py", line 1176, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
LookupError: unknown encoding: ascii
Call stack:
  File "/home/administrator/ros/noetic/system/src/hero_bringup/src/hero_bringup/robot_service.py", line 214, in __del__
    rospy.loginfo("Destructor")
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/core.py", line 190, in loginfo
    _base_logger(msg, args, kwargs, level='info')
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/core.py", line 183, in _base_logger
    logfunc(msg, *args, **kwargs)
Message: 'Destructor'
Arguments: ()
shutting down processing monitor...
... shutting down processing monitor complete
```

**Comment by MatthijsBurgh** [comment]
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/handlers.py", line 69, in emit
    if self.shouldRollover(record):
  File "/usr/lib/python3.8/logging/handlers.py", line 183, in shouldRollover
    self.stream = self._open()
  File "/usr/lib/python3.8/logging/__init__.py", line 1176, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
NameError: name 'open' is not defined
Call stack:
  File "/opt/ros/noetic/lib/python3/dist-packages/hsrb_interface/robot.py", line 146, in __del__
    rospy.signal_shutdown('shutdown')
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/core.py", line 560, in signal_shutdown
    _logger.info("signal_shutdown [%s]"%reason)
Message: 'signal_shutdown [shutdown]'
Arguments: ()
```
